set -g default-terminal "xterm-256color"

unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

# These split panes into current path.
bind '"' split-window -v -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"

set -g mouse on

bind-key -T copy-mode 'v' send-keys -X begin-selection

# vim-like pane resizing
bind -r C-k resize-pane -U
bind -r C-j resize-pane -D
bind -r C-h resize-pane -L
bind -r C-l resize-pane -R

# vim-like pane switching
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
bind -r u last-window

# and now unbind keys
unbind Up
unbind Down
unbind Left
unbind Right

unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right
